controller:
  config:
    server-tokens: "false"
  service:
    loadBalancerIP: "35.187.22.234"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50

rbac:
  create: true
  serviceAccountName: default
